version: '3.5'

services:
    #    db:
    #        image: binhua/mysql
    #        container_name: first-mysql
    #        env_file: ./db.env
    #        restart: always
    #        ports:
    #            - "53306:3306"
    #        volumes:
    #            - /Users/binhualiao/Project/Docker/mysql/lib:/var/lib/mysql:rw
    #            - /Users/binhualiao/Project/Docker/mysql/logs:/var/lib/mysql-logs:rw
    #            - /Users/binhualiao/Project/Docker/mysql/conf.d:/etc/mysql/conf.d:ro
    #        command: "--character-set-server=utf8"
    #        working_dir: /Users/binhualiao/Project/Docker/mysql/mysql_data_init

    web:
        image: binhua/django-first
        container_name: my-django
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ../src:/code
        ports:
            - "8000:8000"
        restart: always
        working_dir: /code
        #        depends_on:
        #            - db
        #        links:
        #            - db
        networks:
            my-web-net:
                aliases:
                    - db
networks:
    my-web-net:
        external: true
